Tristan Baudoux  
LMAPR1492 - tâche 6  
07/03/22  
Objectifs :
- Télécharger le fichier CIF du matériau qui nous a été attribué.
- Etudier l’effet de 3 éléments de symétrie différents (pas l’identité) chacun pour 1 atome différent (équations et représentations)

## Imports :

In [20]:
from pymatgen.ext.matproj import MPRester
from pymatgen import Lattice, Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.io.cif import CifWriter
from pymatgen.core.operations import SymmOp
import numpy as np
from jupyter_jsmol import JsmolView
from jupyter_jsmol.pymatgen import quick_view
from IPython.display import Image
from ipywidgets import Layout, widgets, interact

## Téléchargement du fichier CIF du matériau attribué :
Repris de la tâche 4 et 5

In [21]:
with MPRester("DX9Ul1PoZnBi6AJt") as m:

    # Structure for material id
    structure = m.get_structure_by_material_id("mp-866132")
    
    w = CifWriter(structure,symprec=1e-5);
    w.write_file('Na2TlSb.cif')
    
structure.to(filename="Na2TlSb.cif")

# Pour les étapes qui suivent,
# je préfère travailler sur le fichier cif "symmetrized" que j'upload dans le dossier et ci-dessous je l'utilise :
struct = Structure.from_file("Na2TlSb_mp-866132_symmetrized.cif")

#struct_V2 = Structure.from_file("Na2TlSb.cif")

In [22]:
print(struct)

Full Formula (Na8 Tl4 Sb4)
Reduced Formula: Na2TlSb
abc   :   7.619546   7.619546   7.619546
angles:  90.000000  90.000000  90.000000
Sites (16)
  #  SP       a     b     c
---  ----  ----  ----  ----
  0  Na    0.25  0.25  0.25
  1  Na    0.75  0.75  0.75
  2  Na    0.75  0.25  0.25
  3  Na    0.25  0.75  0.75
  4  Na    0.75  0.75  0.25
  5  Na    0.25  0.25  0.75
  6  Na    0.25  0.75  0.25
  7  Na    0.75  0.25  0.75
  8  Tl    0     0     0
  9  Tl    0.5   0.5   0
 10  Tl    0.5   0     0.5
 11  Tl    0     0.5   0.5
 12  Sb    0     0     0.5
 13  Sb    0.5   0     0
 14  Sb    0     0.5   0
 15  Sb    0.5   0.5   0.5


## Atomes choisis :
Il faut choisir 3 atomes sur lesquels on va effectuer les opérations de symétrie.  
J'affiche ici leurs coordonnées cartésiennes. 

In [43]:
coords = struct.cart_coords
#print(coords) #Affiche les coordonnées de tous les atomes du cif

Na_1 = coords[0]
Tl_1 = coords[11]
Sb_1 = coords[12]
print (" Coordonnées de l'atome de Na choisi (#1 ?):", Na_1, "\n Coordonnées de l'atome de Tl choisi (#4 ?): ",Tl_1, 
       "\n Coordonnées de l'atome de Sb choisi (#1 ?):", Sb_1)


#print("\n")
#coords_V2 = struct_V2.cart_coords
#print("Coordonnées du cif de base : \n")
#print(coords_V2)
#Seulement 4 atomes d'où la raison de prendre le cif symmetrized

 Coordonnées de l'atome de Na choisi (#1 ?): [1.9048865 1.9048865 1.9048865] 
 Coordonnées de l'atome de Tl choisi (#4 ?):  [6.12658225e-16 3.80977300e+00 3.80977300e+00] 
 Coordonnées de l'atome de Sb choisi (#1 ?): [0.       0.       3.809773]


## Premier élément de symétrie : la translation

$$
\left(\begin{array}{cc} 
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1\\
\end{array}\right)
\left(\begin{array}{cc} 
x\\ 
y\\
z\\
\end{array}\right)
+ 
\left(\begin{array}{cc} 
3.80977\\ 
0\\
0\\
\end{array}\right)
= 
\left(\begin{array}{cc} 
x+3.80977 \\ 
y \\
z \\
\end{array}\right)
$$

In [24]:
Op1 = SymmOp.from_xyz_string('x+3.80977, y, z')
sym1 = Op1.operate(Na_1)
print("Symétrie 1 : Translation")
print('_______________________________\n')
print("La matrice de rotation associée à la symétrie 'x+3.80977, y, z' :\n",Op1.rotation_matrix)
print("Le vecteur de translation associé à la symétrie 'x+3.80977, y, z' :\n", Op1.translation_vector,"\n")
print("On applique la symétrie sur l'atome Na :")
print("Atome de départ : ",str(Na_1) )
print("Atome d'arrivée : ",str(sym1))
print("Nous avons ici effectué une translation le long de l'axe x.")

Symétrie 1 : Translation
_______________________________

La matrice de rotation associée à la symétrie 'x+3.80977, y, z' :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Le vecteur de translation associé à la symétrie 'x+3.80977, y, z' :
 [3.80977 0.      0.     ] 

On applique la symétrie sur l'atome Na :
Atome de départ :  [1.9048865 1.9048865 1.9048865]
Atome d'arrivée :  [5.7146565 1.9048865 1.9048865]
Nous avons ici effectué une translation le long de l'axe x.


In [42]:
view1 = quick_view(struct, "packed", supercell=[1, 1, 1])
display(view1)

#Rien ne s'affiche sur mon ordi :/ Ai-je fais une erreur quelque part ? 

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [37]:
view1.script("draw symop 1 {atomno=1}")
#Rien ne veut s'afficher ici non plus quand je met des valeurs plausibles et je ne suis pas sûr d'avoir compris comment déterminer
#le numéro de l'atome que j'ai choisi et l'opération de symétrie effectuée :/ 

## Deuxième élément de symétrie : le plan miroir


$$
\left(\begin{array}{cc} 
0 & -1 & 0\\
-1 & 0 & 0\\
0 & 0 & -1\\
\end{array}\right)
\left(\begin{array}{cc} 
x\\ 
y\\
z\\
\end{array}\right)
+ 
\left(\begin{array}{cc} 
0\\ 
0\\
0\\
\end{array}\right)
= 
\left(\begin{array}{cc} 
-y \\ 
-x \\
z \\
\end{array}\right)
$$

In [27]:
Op2 = SymmOp.from_xyz_string('-y, -x, z')
sym2 = Op2.operate(Tl_1)
print("Symétrie 2 : Plan miroir")
print('_______________________________\n')
print("La matrice de rotation associée à la symétrie '-y, -x, z' :\n",Op2.rotation_matrix)
print("Le vecteur de translation associé à la symétrie '-y, -x, z' :\n", Op2.translation_vector,"\n")
print("On applique la symétrie sur l'atome Tl :")
print("Atome de départ : ",str(Tl_1) )
print("Atome d'arrivée : ",str(sym2))
print("")

Symétrie 2 : Plan miroir
_______________________________

La matrice de rotation associée à la symétrie '-y, -x, z' :
 [[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
Le vecteur de translation associé à la symétrie '-y, -x, z' :
 [0. 0. 0.] 

On applique la symétrie sur l'atome Tl :
Atome de départ :  [6.12658225e-16 3.80977300e+00 3.80977300e+00]
Atome d'arrivée :  [-3.80977300e+00 -6.12658225e-16  3.80977300e+00]



In [28]:
view2 = quick_view(struct, "packed", supercell = [1,1,1])
display(view2)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [29]:

view2.script("draw symop ? {atomno=?}")

## Troisième élément de symétrie : l'inversion

$$
\left(\begin{array}{cc} 
-1 & 0 & 0\\
0 & -1 & 0\\
0 & 0 & -1\\
\end{array}\right)
\left(\begin{array}{cc} 
x\\ 
y\\
z\\
\end{array}\right)
+ 
\left(\begin{array}{cc} 
0\\ 
0\\
0\\
\end{array}\right)
= 
\left(\begin{array}{cc} 
-x \\ 
-y \\
-z \\
\end{array}\right)
$$

In [31]:
Op3 = SymmOp.from_xyz_string('-x, -y, -z')
sym3 = Op3.operate(Sb_1)
print("Symétrie 3 : Inversion")
print('_______________________________\n')
print("La matrice de rotation associée à la symétrie '-x, -y, -z' :\n",Op3.rotation_matrix)
print("Le vecteur de translation associé à la symétrie '-x, -y, -z' :\n", Op3.translation_vector,"\n")
print("On applique la symétrie sur l'atome Sb :")
print("Atome de départ : ",str(Sb_1) )
print("Atome d'arrivée : ",str(sym3))
print("")

Symétrie 3 : Inversion
_______________________________

La matrice de rotation associée à la symétrie '-x, -y, -z' :
 [[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
Le vecteur de translation associé à la symétrie '-x, -y, -z' :
 [0. 0. 0.] 

On applique la symétrie sur l'atome Sb :
Atome de départ :  [0.       0.       3.809773]
Atome d'arrivée :  [ 0.        0.       -3.809773]



In [32]:
view3 = quick_view(struct, "packed", supercell = [1,1,1])
display(view3)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [33]:

view3.script("draw symop ? {atomno=?}")